#!/usr/bin/python3

import subprocess as sp
import argparse
import os
import time
import random

res=0
uid=""
idnum=55

def check_if_has(lines,itms):
    """check_if_has checks to see if any item in itms is in the lines"""
    for x in itms:
        for l in lines:
            if x in l:
                print(l)
                return True
    return False

trailers="\n\r\t "

def runecho(args,timeout=10.0):
    p1=sp.Popen(args,stderr=sp.STDOUT,stdout=sp.PIPE,encoding="utf-8")
    tstart=time.time()
    rv=[]
    cline=""
    while True:
        oc=p1.stdout.read(1)
        if not oc:
            time.sleep(0.10)
            if p1.poll()!=None:
                if len(cline)>0:
                   rv.append(cline)
                return rv
            if (time.time()-tstart)>timeout :
                p1.kill()
                if len(cline)>0:
                   rv.append(cline)
                print("Timeout")
                rv.append("Timeout")
                return rv
        else:
           print(oc,end="")
           if oc=="\n":
               rv.append(cline)
               cline=""
           else:
               cline+=oc
    if len(cline)>0:
       rv.append(cline)
    return rv


def runsynthesis(clkperiod,idnum):
    global uid
    simres="No returned result\n"
    try:
        os.remove("synthesis.script")
    except:
        pass
    with open("synthesis.script","w") as fs:
        fs.write("""set link_library {{/home/morris/FreePDK45/osu_soc/lib/files/gscl45nm.db /apps/synopsys/PrimeTimeNew/pts/Q-2019.12/libraries/syn/dw_foundation.sldb}}
set target_library {{/home/morris/FreePDK45/osu_soc/lib/files/gscl45nm.db}}
suppress_message {{ UID-401 VER-130 }}
read_sverilog hw1_{2:02d}.v
current_design hw1_{2:02d}
create_clock clk -name clk -period {1:5.3f}
set_propagated_clock clk
set_clock_uncertainty 0.25 clk
set_propagated_clock clk
set_output_delay 0.5 -clock clk [all_outputs]
set all_inputs_wo_rst_clk [remove_from_collection [remove_from_collection [all_inputs] [get_port clk]] [get_port reset]]
set_driving_cell -lib_cell NAND2X1 $all_inputs_wo_rst_clk
set_input_delay 0.6 -clock clk $all_inputs_wo_rst_clk
set_output_delay 0.6 -clock clk [all_outputs]
set_fix_hold [ get_clocks clk ]
set_output_delay 0.3 -clock clk [all_outputs]
set_max_delay {1:5.3f} -from [all_inputs] -to [all_outputs]
compile_ultra
create_clock clk -name clk -period {0:5.3f}

update_timing
report_timing -max_paths 5
write -hierarchy -format verilog -output hw1_{2:02d}_gates.v
quit

""".format(clkperiod,clkperiod*0.7,idnum))
    try:
        os.remove("HW1_{:02d}_gates.v".format(idnum))
    except:
        pass
    cwd=runecho(['pwd'])[0]
    try:
        random.seed(idnum)
        cadbox=random.randint(0,2)
        with open("sss","w") as fs:
            fs.write(f"""#!/usr/bin/csh
cd {cwd}
source /apps/design_environment.csh
dc_shell -f synthesis.script | tee synres.txt
""")
        os.chmod("sss",0o705)
        arg=["./sss"]
        simres=runecho(arg,timeout=800)
    except:
        print("Synthesis didn't work")
        print(simres)
        res.write("synthesis didn't run\n")
        return False
    lines=simres
    print("num returned lines",len(lines))
    if check_if_has(lines,["Latch","latch","Error","error"," arc","loop","Loop",
                           "violated","Violated","VIOLATED","ERROR","LATCH"]):
        print("Synthesis has errors")
        res.write("Synthesis failed\n")
        return False
    res.write("Synthesis worked ish\n")
    return True

def runvcs(idnum):
    sp.call(["rm","-rf","simv","simv.daidir","csrc","*.vcd"])
    simres="No returned result\n"
    try:
        arg=["./sv_vcs","hw1_{:02d}_tb.v".format(idnum)]
        simres=runecho(arg,timeout=100)
    except:
        print("Simulation didn't work")
        print(simres)
        res.write("VCS didn't run\n")
        return False
    lines=simres
    if check_if_has(lines,["Error","= ="]) :
        print("VCS simulation failed\n")
        res.write("VCS simulation failed\n")
        return False
    if not check_if_has(lines,["Oh happy time, it worked"]):
        print("VCS simulation didn't complete successfully")
        res.write("VCS didn't complete successfully\n")
        return False
    res.write("VCS simulation ran\n")
    print("\n\n\nVCS simulation worked\n\n")
    return True


def rungates(idnum):
    sp.call(["rm","-rf","simv","simv.daidir","csrc","*.vcd"])
    simres="No returned result\n"
    try:
        arg=["./sv_vcs","/home/morris/FreePDK45/osu_soc/lib/files/gscl45nm.v","hw1_{:02d}_tbgates.v".format(idnum)]
        simres=runecho(arg,timeout=100)
    except:
        print("Simulation didn't work")
        print(simres)
        res.write("VCS didn't run\n")
        return False
    lines=simres
    if check_if_has(lines,["Error","= ="]) :
        print("VCS simulation failed\n")
        res.write("VCS simulation failed\n")
        return False
    if not check_if_has(lines,["Oh happy time, it worked"]):
        print("VCS simulation didn't complete successfully")
        res.write("VCS didn't complete successfully\n")
        return False
    res.write("VCS simulation ran\n")
    print("\n\n\nVCS simulation worked\n\n")
    return True



def gethwnum():
    global idnum
    with open("hwnum.txt","r") as fi:
        l=fi.readline()
        l=l.strip()
        idnum=int(l)

def sethwnum():
    with open("hwnum.txt","w") as fo:
        fo.write("{:02d}\n".format(idnum))

def main():
    global res,uid,idnum
    clkperiod=40.0
    resfn="results.txt"
    parser=argparse.ArgumentParser(description='287 S24 HW1')
    parser.add_argument("--clkperiod",default=40.0)
    parser.add_argument("--resultsFileName",default="results.txt")
    parser.add_argument("--hwnum",default=55)
    uid=runecho(['id','-un'])[0]
    print(uid)
    args = parser.parse_args()
    print(args)
    if os.path.exists("hwnum.txt"):
        gethwnum()
    else:
        if args.hwnum==55:
            print("You need to use --hwnum the first time to set your number")
            return
        else:
            idnum=int(args.hwnum)
            sethwnum()

    resfn=args.resultsFileName
    clkperiod=float(args.clkperiod)
    with open(resfn,"w") as res:
        res.write("HW run for user {} assignment id {}\n".format(uid,idnum))
        res.write("Run at {}\n".format(time.asctime(time.localtime(time.time()))))
        if not runvcs(idnum):
            return
        if not runsynthesis(clkperiod,idnum):
            return
        if not rungates(idnum):
            return
        res.write("HW worked\n")

main()

